server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts: 
      - prometheus.node-01
    path: /
    pathType: Prefix

  persistentVolume:
    enabled: true
    mountPath: /data

  extraArgs:
    web.enable-otlp-receiver: ""
    web.enable-remote-write-receiver: ""

alertmanager:
  enabled: true
  persistence:
    enabled: true

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
  rbac:
    pspEnabled: false
  containerSecurityContext:
    allowPrivilegeEscalation: false

prometheus-pushgateway:
  enabled: true

