apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-info
  namespace: sample
spec:
  ingressClassName: nginx
  rules:
  - host: bookinfo.node-01
    http:
      paths:
      - backend:
          service:
            name: productpage
            port:
              number: 9080
        path: /
        pathType: Prefix
